### ISSUE TITLE
Add documentation links

### ISSUE THREAD

**Issue by darthdeus** [mbuczko/awesome-clojure#1]
There are many useful documentation browsers
- http://conj.io/
- http://clojuredocs.org/
- http://crossclj.info/

and maybe even http://clojure-doc.org/, which is more of a tutorial style, but certainly helpful

**Comment by hura** [comment]
Other candidates:

http://jafingerhut.github.io/
http://cljs.info/cheatsheet/
https://github.com/martintrojer/go-tutorials-core-async
https://github.com/halgari/clojure-conj-2013-core.async-examples/blob/master/src/clojure_conj_talk/core.clj

https://aphyr.com/posts/319-clojure-from-the-ground-up-debugging

**Comment by mbuczko** [comment]
thanks, added. core.async resources pushed to the "projects" section.
